backend/config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => "/api-docs"
  mount Rswag::Api::Engine => "/api-docs"

  resources :posts do
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  devise_for :users,
    controllers: {
      sessions: "users/sessions",
      registrations: "users/registrations",
    }

  resources :users, only: [:show, :index]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

backend/app/models/post.rb
# frozen_string_literal: true
class Post < ApplicationRecord
  mount_uploader :picture, PictureUploader

  # Associations
  belongs_to :user
  has_many :likes
  has_many :users_with_like, through: :likes, source: :user
  has_many :comments
end

backend/app/controllers/posts_controller.rb
# frozen_string_literal: true
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    if @post.user_id != current_user.id
      respond_to do |format|
        format.html { redirect_to(@post, notice: "You don't have permissions.") }
        format.json { head(:forbidden) }
      end
    end
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, notice: "Post was successfully created.") }
        format.json { render(:show, status: :created, location: @post) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @post.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.user_id != current_user.id
        format.html { redirect_to(@post, notice: "You don't have permissions.") }
        format.json { head(:forbidden) }
      elsif @post.update(post_params)
        format.html { redirect_to(@post, notice: "Post was successfully updated.") }
        format.json { render(:show, status: :ok, location: @post) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @post.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    respond_to do |format|
      if @post.user_id != current_user.id
        format.html { redirect_to(@post, notice: "You don't have permissions.") }
        format.json { head(:forbidden) }
      else
        @post.destroy
        format.html { redirect_to(posts_url, notice: "Post was successfully destroyed.") }
        format.json { head(:no_content) }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:description, :picture, :remote_picture_url)
  end
end

backend/app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

backend/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Picture</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.description %></td>
        <td>
          <% if post.picture.present? %>
            <%= image_tag post.picture_url, size: '100x100'  %>
          <%end %>
        </td>
        <td><%= post.user_id %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

backend/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

backend/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Picture:</strong>

  <% if @post.picture.present? %>
    <%= image_tag @post.picture_url, size: '200x200'  %>
  <%end %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>